version: '3.7'

services:
  chat:
    image: ${APP_IMAGE}
#    for producation,请注释command行即可
#    for beta
    command: python manage.py runserver 0.0.0.0:8000
    # 生产环境中请使用自动重启; always
    restart: unless-stopped
    ports:
       - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - data_static:/opt/app/static

#  web:
#      image: nginx:1.21.0
#      restart: unless-stopped
#      links:
#        - chat:app
#      ports:
#        - "8000:80"
#      environment:
#        - TZ=Asia/Shanghai
#      volumes:
#        - ./config/default_nginx.conf:/etc/nginx/conf.d/default.conf
#        - data_nginx_log:/var/log/nginx
#        - data_static:/opt/app/static/

volumes:
  data_nginx_log:
    driver: local
  data_static:
    driver: local