name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # 仅当推送的标签匹配 v* 模式时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: 配置Python编译器
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Get project name
        id: get_project_name
        run: |
          repo_name=${GITHUB_REPOSITORY##*/}
          echo "repo_name=$repo_name" >> $GITHUB_ENV

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Remove 'v' prefix from tag
        id: remove_v_prefix
        run: |
          tag_without_v=${{ env.latest_tag#v }}
          echo "Tag without 'v': $tag_without_v"
          echo "tag_without_v=$tag_without_v" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/liaozhiming/${{ env.repo_name }}:a${{ env.$tag_without_v }}
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/liaozhiming/${{ env.repo_name }}:a${{ env.$tag_without_v }}
